sudo: false
language: ruby
rvm:
    - 2
bundler_args: --without development --deployment --jobs=3 --retry=3
cache: bundler
script:
    - bundle exec jekyll build
branches:
    only:
        - gh-pages
