# Site settings
name: Notizblog
email: mail@danny-edel.de
description: "Things I don't want to forget. This is for my personal use, and not meant as a public service."
url: "http://blog.danny-edel.de"
twitter_username:
github_username:  dannyedel
author:
    name: Danny Edel
    email: mail@danny-edel.de

gems:
  - jekyll-feed
  - jekyll-gist

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Build settings
permalink: pretty

# make as github-ish as possible
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter_opts:
        line_numbers: false
        class: hll

lsi: false
source: .

# default-layout for all posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
