# Site settings
title: My Blog
email: mail@danny-edel.de
description: "Some things I don't want to forget. Mainly of use for myself."
url: "http://blog.danny-edel.de"
twitter_username:
github_username:  dannyedel

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Build settings
permalink: pretty

# make as github-ish as possible
markdown: redcarpet
redcarpet:
  extensions:
    - autolink
    - with_toc_data

highlighter: pygments

# mimick github
# fixed
safe: true
lsi: false
source: .

# default-layout for all posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
